from audio_notes import *


def happy_birthday_to_you():
    BPM = 160
    duration = get_note_duration(BPM)

    melody = [
        (get_lower_octave(G), duration["semínima"]),
        (get_lower_octave(G), duration["semínima"]),
        (get_lower_octave(A), duration["mínima"]),
        (get_lower_octave(G), duration["mínima"]),
        (C, duration["mínima"]),
        (get_lower_octave(B), duration["semibreve"]),

        (get_lower_octave(G), duration["semínima"]),
        (get_lower_octave(G), duration["semínima"]),
        (get_lower_octave(A), duration["mínima"]),
        (get_lower_octave(G), duration["mínima"]),
        (D, duration["mínima"]),
        (C, duration["semibreve"]),

        (get_lower_octave(G), duration["semínima"]),
        (get_lower_octave(G), duration["semínima"]),
        (G, duration["mínima"]),
        (E, duration["mínima"]),
        (C, duration["mínima"]),
        (get_lower_octave(B), duration["mínima"]),
        (get_lower_octave(A), duration["semibreve"]),

        (F, duration["semínima"]),
        (F, duration["semínima"]),
        (E, duration["mínima"]),
        (C, duration["mínima"]),
        (D, duration["mínima"]),
        (C, duration["breve"])
    ]

    save_melody("happy_birthday_to_you.wav", melody)


def ode_to_joy():
    BPM = 160
    duration = get_note_duration(BPM)

    melody = [
        (E, duration["semínima"]),
        (E, duration["semínima"]),
        (F, duration["semínima"]),
        (G, duration["semínima"]),
        (G, duration["semínima"]),
        (F, duration["semínima"]),
        (E, duration["semínima"]),
        (D, duration["semínima"]),
        (C, duration["semínima"]),
        (C, duration["semínima"]),
        (D, duration["semínima"]),
        (E, duration["semínima"]),
        (E, duration["semínima"]),
        (D, duration["semínima"]),
        (D, duration["semínima"]),
        (E, duration["semínima"]),
        (E, duration["semínima"]),
        (F, duration["semínima"]),
        (G, duration["semínima"]),
        (G, duration["semínima"]),
        (F, duration["semínima"]),
        (E, duration["semínima"]),
        (D, duration["semínima"]),
        (C, duration["semínima"]),
        (C, duration["semínima"]),
        (D, duration["semínima"]),
        (E, duration["semínima"]),
        (D, duration["semínima"]),
        (C, duration["semínima"])
    ]

    save_melody("ode_to_joy.wav", melody)


def il_vento_doro():
    BPM = 200
    duration = get_note_duration(BPM)

    melody = [
        (D, duration["colcheia"]),
        (D_FLAT, duration["semicolcheia"]),
        (get_lower_octave(B), duration["semínima"]),
        (get_lower_octave(A), duration["semínima"] + duration["colcheia"]),
        (get_lower_octave(B), duration["semínima"]),
        (SILENCE, duration["colcheia"]),
        (get_lower_octave(B), duration["semínima"]),
        (SILENCE, duration["colcheia"]),
        (get_lower_octave(F_SHARP), duration["semínima"]),
        (get_lower_octave(A), duration["semínima"]),
        (get_lower_octave(B), duration["semínima"]),
        (D_FLAT, duration["semínima"] + duration["colcheia"]),
        (get_lower_octave(A), duration["semínima"]),
        (get_lower_octave(B), duration["mínima"]),
        (SILENCE, duration["colcheia"]),
        (D, duration["colcheia"] + duration["semicolcheia"]),
        (D_FLAT, duration["colcheia"]),
        (get_lower_octave(B), duration["semínima"]),
        (get_lower_octave(A), duration["semínima"] + duration["colcheia"]),
        (get_lower_octave(B), duration["semínima"]),
        (SILENCE, duration["semicolcheia"]),
        (get_lower_octave(B), duration["semínima"]),
        (SILENCE, duration["semicolcheia"]),
        (get_lower_octave(F_SHARP), duration["colcheia"]),
        (D_FLAT, duration["semínima"]),
        (D, duration["semínima"]),
        (D_FLAT, duration["semínima"] + duration["colcheia"]),
        (get_lower_octave(A), duration["semínima"]),
        (get_lower_octave(E), duration["mínima"]),
        (SILENCE, duration["colcheia"]),
        (D, duration["colcheia"] + duration["semicolcheia"]),
        (D_FLAT, duration["colcheia"]),
        (get_lower_octave(B), duration["semínima"]),
        (get_lower_octave(A), duration["semínima"] + duration["colcheia"]),
        (get_lower_octave(B), duration["semínima"]),
        (SILENCE, duration["semicolcheia"]),
        (get_lower_octave(B), duration["semínima"]),
        (SILENCE, duration["semicolcheia"]),
        (get_lower_octave(F_SHARP), duration["semínima"]),
        (get_lower_octave(A), duration["semínima"]),
        (get_lower_octave(B), duration["semínima"]),
        (D_FLAT, duration["semínima"] + duration["colcheia"]),
        (get_lower_octave(A), duration["semínima"]),
        (get_lower_octave(B), duration["mínima"]),
        (SILENCE, duration["colcheia"]),
        (D, duration["colcheia"] + duration["semicolcheia"]),
        (D_FLAT, duration["colcheia"]),
        (get_lower_octave(B), duration["semínima"]),
        (get_lower_octave(A), duration["semínima"]),
        (D_FLAT, duration["semínima"]),
        (F_SHARP, duration["semínima"]),
        (E, duration["semínima"]),
        (E_FLAT, duration["semínima"]),
        (B, duration["semínima"]),
        (A, duration["semínima"]),
        (A_FLAT, duration["semínima"]),
        (F_SHARP, duration["semínima"]),
        (D, duration["semínima"]),
        (D_FLAT, duration["semínima"]),
        (get_lower_octave(B), duration["colcheia"]),
        (get_lower_octave(A), duration["colcheia"]),
        (get_lower_octave(B), duration["colcheia"]),
        (SILENCE, duration["semicolcheia"]),
        (get_lower_octave(A), duration["colcheia"]),
        (get_lower_octave(B), duration["colcheia"]),
        (SILENCE, duration["semicolcheia"]),
        (get_lower_octave(A), duration["colcheia"]),
        (get_lower_octave(B), duration["colcheia"]),
        (SILENCE, duration["semicolcheia"]),
        (get_lower_octave(A), duration["colcheia"]),
        (get_lower_octave(B), duration["colcheia"]),
        (SILENCE, duration["semicolcheia"]),
        (get_lower_octave(A), duration["colcheia"]),
        (get_lower_octave(B), duration["colcheia"]),

        # REFRÃO
        (D, duration["semínima"]),
        (F_SHARP, duration["mínima"]),
        (SILENCE, duration["colcheia"]),
        (D, duration["mínima"] + duration["semínima"]),
        (SILENCE, duration["semínima"]),
        (D, duration["semínima"]),
        (E, duration["semínima"]),
        (F, duration["mínima"]),
        (E, duration["mínima"]),
        (D, duration["semínima"]),
        (D_FLAT, duration["semínima"] + duration["colcheia"]),
        (D, duration["semínima"] + duration["colcheia"]),
        (E, duration["semínima"]),
        (F_SHARP, duration["mínima"]),
        (SILENCE, duration["colcheia"]),
        (B, duration["mínima"] + duration["semínima"]),
        (SILENCE, duration["semínima"]),
        (get_lower_octave(B), duration["semínima"]),
        (D_FLAT, duration["semínima"]),
        (D, duration["semínima"] + duration["colcheia"]),
        (E, duration["semínima"] + duration["colcheia"]),
        (D, duration["semínima"]),
        (D_FLAT, duration["semínima"] + duration["colcheia"]),
        (A, duration["semínima"] + duration["colcheia"]),
        (G, duration["semínima"]),
        (F_SHARP, duration["mínima"]),
        (SILENCE, duration["semínima"]),
        (D, duration["mínima"] + duration["semínima"]),
        (SILENCE, duration["semínima"]),
        (D, duration["semínima"]),
        (E, duration["semínima"]),
        (F, duration["mínima"]),
        (E, duration["mínima"]),
        (D, duration["semínima"]),
        (D_FLAT, duration["semínima"] + duration["colcheia"]),
        (D, duration["semínima"] + duration["colcheia"]),
        (E, duration["semínima"]),
        (F_SHARP, duration["mínima"]),
        (SILENCE, duration["colcheia"]),
        (B, duration["mínima"] + duration["semínima"]),
        (SILENCE, duration["semínima"]),
        (B, duration["semínima"]),
        (get_upper_octave(D_FLAT), duration["semínima"]),
        (get_upper_octave(D), duration["semínima"] + duration["colcheia"]),
        (G, duration["semínima"] + duration["colcheia"]),
        (F_SHARP, duration["semínima"]),
        (F, duration["mínima"]),
        (get_upper_octave(D), duration["semínima"] + duration["colcheia"]),
        (B_FLAT, duration["semínima"]),

        (get_lower_octave(B), duration["semínima"]),
        (get_lower_octave(B), duration["semínima"]),
        (get_lower_octave(A), duration["semínima"]),
        (get_lower_octave(B), duration["semínima"]),
        (D, duration["semínima"]),
        (get_lower_octave(B), duration["semínima"]),
        (get_lower_octave(F_SHARP), duration["colcheia"]),
        (get_lower_octave(A), duration["semínima"]),
        (get_lower_octave(B), duration["semínima"]),
        (get_lower_octave(B), duration["semínima"]),
        (get_lower_octave(B), duration["semínima"]),
        (get_lower_octave(A), duration["semínima"]),
        (get_lower_octave(B), duration["semínima"]),
        (F, duration["semínima"]),
        (E, duration["semínima"]),
        (D, duration["semínima"]),
        (get_lower_octave(A), duration["semínima"]),
        (get_lower_octave(B), duration["semínima"]),
        (get_lower_octave(B), duration["semínima"]),
        (get_lower_octave(B), duration["semínima"]),
        (get_lower_octave(A), duration["semínima"]),
        (get_lower_octave(B), duration["semínima"]),
        (D, duration["semínima"]),
        (get_lower_octave(B), duration["semínima"]),
        (get_lower_octave(F_SHARP), duration["colcheia"]),
        (get_lower_octave(A), duration["semínima"]),
        (get_lower_octave(B), duration["semínima"]),
        (get_lower_octave(B), duration["semínima"]),
        (get_lower_octave(B), duration["semínima"]),
        (get_lower_octave(A), duration["semínima"]),
        (get_lower_octave(B), duration["semínima"]),
        (D, duration["semínima"]),
        (F, duration["semínima"]),
        (E, duration["semínima"]),
        (D, duration["semínima"]),
        (get_lower_octave(A), duration["semínima"]),
        (get_lower_octave(B), duration["semínima"]),
        (get_lower_octave(B), duration["semínima"]),
        (get_lower_octave(B), duration["semínima"]),
        (get_lower_octave(A), duration["semínima"]),
        (get_lower_octave(B), duration["semínima"]),
        (D, duration["semínima"]),
        (get_lower_octave(B), duration["semínima"]),
        (get_lower_octave(F_SHARP), duration["colcheia"]),
        (get_lower_octave(A), duration["semínima"]),
        (get_lower_octave(B), duration["semínima"]),
        (get_lower_octave(B), duration["semínima"]),
        (get_lower_octave(B), duration["semínima"]),
        (get_lower_octave(A), duration["semínima"]),
        (get_lower_octave(B), duration["semínima"]),
        (F, duration["semínima"]),
        (E, duration["semínima"]),
        (D, duration["semínima"]),
        (get_lower_octave(A), duration["semínima"]),
        (get_lower_octave(B), duration["semínima"]),
        (get_lower_octave(B), duration["semínima"]),
        (get_lower_octave(B), duration["semínima"]),
        (get_lower_octave(A), duration["semínima"]),
        (get_lower_octave(B), duration["semínima"]),
        (D, duration["semínima"]),
        (get_lower_octave(B), duration["semínima"]),
        (get_lower_octave(F_SHARP), duration["colcheia"]),
        (get_lower_octave(A), duration["semínima"]),
        (get_lower_octave(B), duration["semínima"]),
        (get_lower_octave(B), duration["semínima"]),
        (get_lower_octave(B), duration["semínima"]),
        (get_lower_octave(A), duration["semínima"]),
        (get_lower_octave(B), duration["semínima"]),
        (D, duration["semínima"]),
        (D, duration["semínima"]),
    ]

    save_melody("il_vento_doro.wav", melody)


il_vento_doro()
# ode_to_joy()
# happy_birthday_to_you()


